# Values used for the deployed application.
replicaCount: 2
eksCluster: true
service:
  name: native-ingester-metadata
env:
  QUEUE_READ_GROUP: "nativeIngesterMetadata"
  QUEUE_READ_TOPIC: "PreNativeCmsMetadataPublicationEvents"
  NATIVE_CONTENT_UUID_FIELDS: "uuid,post.uuid,data.uuidv3,id"
  CONFIG: "config_metadata.json"
  QUEUE_WRITE_TOPIC: "NativeCmsMetadataPublicationEvents"
  CONTENT_TYPE: "Annotations"
  PANIC_GUIDE_URL: "https://runbooks.in.ft.com/native-ingester-metadata"
resources:
  requests:
    memory: 200Mi
  limits:
    memory: 512Mi
